#!/bin/sh

#optional arguments
# ARG1=${1:-color1}
# ARG2=${2:-color2}

#hostname
read -r host < /proc/sys/kernel/hostname

#os (distro)
read -r kernel < /proc/sys/kernel/osrelease
. /etc/os-release

#de
de=$DESKTOP_SESSION;

#up
up=$(uptime -p | awk '{ print substr( $0, 4 ) }' | sed 's|[,]||g')


#wm
  [ ! "$wm" ] && [ "$DISPLAY" ] && command -v xprop >/dev/null && {
    id=$(xprop -root -notype _NET_SUPPORTING_WM_CHECK)
    id=${id##* }
    wm=$(xprop -id "$id" -notype -len 100 -f _NET_WM_NAME 8t |
      grep '^_NET_WM_NAME' | cut -d\" -f 2)
  }

#kernel
read -r _ _ version _ < /proc/version
ke=${version%%-*}

#colors
welcometext='[35m'
infotext='[36m'
white='[37m'
reset='[0m'


# if [ ! -z $1 ]
# then
#   welcometext='[32m'
# fi

#output
printf '%s\n' "
  ${infotext}os${white} ~ ${PRETTY_NAME}
  ${infotext}sh${white} ~ ${SHELL##*/}
  ${infotext}de${white} ~ ${de}
  ${infotext}wm${white} ~ ${wm}
  ${infotext}kr${white} ~ ${ke}
  ${infotext}up${white} ~ ${up}

  welcome to ${welcometext}${host}${reset}, ${welcometext}${USER}${reset}
"
