#!/bin/sh

#optional arguments for the welcome text color
infotextcolor=${1:-}

#optional arguments for the info text color
welcometextcolor=${2:-}

#hostname
read -r host < /proc/sys/kernel/hostname

#os (distro)
read -r kernel < /proc/sys/kernel/osrelease
. /etc/os-release

#de
de=$DESKTOP_SESSION;

#up
up=$(uptime -p | awk '{ print substr( $0, 4 ) }' | sed 's|[,]||g')


#wm
  [ ! "$wm" ] && [ "$DISPLAY" ] && command -v xprop >/dev/null && {
    id=$(xprop -root -notype _NET_SUPPORTING_WM_CHECK)
    id=${id##* }
    wm=$(xprop -id "$id" -notype -len 100 -f _NET_WM_NAME 8t |
      grep '^_NET_WM_NAME' | cut -d\" -f 2)
  }

#kernel
read -r _ _ version _ < /proc/version
ke=${version%%-*}

#colors
white='[37m'
red='[31m'
green='[32m'
yellow='[33m'
blue='[34m'
cyan='[36m'
purple='[35m'

#Default colors
infotext=$blue
welcometext=$green
reset='[0m'

#Infocolors
if [ "$infotextcolor" = "white" ]; then
  infotext=$white
fi

if [ "$infotextcolor" = "red" ]; then
  infotext=$red
fi

if [ "$infotextcolor" = "green" ]; then
  infotext=$green
fi

if [ "$infotextcolor" = "yellow" ]; then
  infotext=$yellow
fi

if [ "$infotextcolor" = "blue" ]; then
  infotext=$blue
fi

if [ "$infotextcolor" = "cyan" ]; then
  infotext=$cyan
fi

if [ "$infotextcolor" = "purple" ]; then
  infotext=$purple
fi

#Welcometext colors
if [ "$welcometextcolor" = "white" ]; then
  welcometext=$white
fi

if [ "$welcometextcolor" = "red" ]; then
  welcometext=$red
fi

if [ "$welcometextcolor" = "green" ]; then
  welcometext=$green
fi

if [ "$welcometextcolor" = "yellow" ]; then
  welcometext=$yellow
fi

if [ "$welcometextcolor" = "blue" ]; then
  welcometext=$blue
fi

if [ "$welcometextcolor" = "cyan" ]; then
  welcometext=$cyan
fi

if [ "$welcometextcolor" = "purple" ]; then
  welcometext=$purple
fi

#output
printf '%s\n' "
  ${infotext}os${white} ~ ${PRETTY_NAME}
  ${infotext}sh${white} ~ ${SHELL##*/}
  ${infotext}de${white} ~ ${de}
  ${infotext}wm${white} ~ ${wm}
  ${infotext}kr${white} ~ ${ke}
  ${infotext}up${white} ~ ${up}

  welcome to ${welcometext}${host}${reset}, ${welcometext}${USER}${reset}
"

if [ ! -z $color ]
then
  echo "You chose the color %s\n" "$color"
fi
